"""add feedback sessions

Revision ID: 34be83bc36d4
Revises: c6317a75556f
Create Date: 2026-09-14 01:17:57.284371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "34be83bc36d4"
down_revision: Union[str, Sequence[str], None] = "c6317a75556f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

feedback_session_status_enum = postgresql.ENUM(
    "AWAITING_BOTH",
    "AWAITING_STUDENT",
    "AWAITING_FACULTY",
    "UNLOCKED",
    name="feedback_session_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    feedback_session_status_enum.create(op.get_bind(), checkfirst=False)
    op.create_table(
        "feedback_sessions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            feedback_session_status_enum,
            server_default="AWAITING_BOTH",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "student_id <> faculty_id",
            name="ck_feedback_sessions_distinct_participants",
        ),
        sa.ForeignKeyConstraint(["faculty_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback_sessions")
    feedback_session_status_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
